services:
   db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: piAdmin
      POSTGRES_PASSWORD: P@$$w0rd
      POSGRES_DATABASE: pi
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: